//
//  AtomIdentifier.swift
//  SwiftTaggerMP4
//
//  Created by Nolaine Crusher on 4/21/20.
//  Copyright © 2020 Nolaine Crusher. All rights reserved.
//

import Foundation

@available(OSX 10.13, *)
enum Metadata: String, CaseIterable {
    
    case acknowledgment = "©cak"
    case album = "©alb"
    case albumArtist = "aART"
    case albumArtistSort = "soaa"
    case albumSort = "soal"
    case arranger = "©arg"
    case artDirector = "©ard"
    case artist = "©ART"
    case artistSort = "soar"
    case artistWebpage = "URL_OFFICIAL_ARTIST_SITE"
    case artwork = "covr"
    case audioFileWebpage = "OFFICIAL_AUDIO_FILE_URL"
    case audioSourceWebpage = "OFFICIAL_AUDIO_SOURCE_URL"
    case bpm = "tmpo"
    case comment = "©cmt"
    case compilation = "cpil"
    case composer = "©wrt"
    case composerSort = "soco"
    case conductor = "©con"
    case contentAdvisory = "iTunEXTC"
    case contentRating = "rtng"
    case copyright = "cprt"
    case copyrightWebpage = "COPYRIGHT URL"
    case description = "©des"
    case director = "©dir"
    case discNumber = "disk"
    case encodedBy = "©enc"
    case encodingSettings = "ENCODING"
    case encodingTime = "ENCODINGTIME"
    case encodingTool = "©too"
    case episodeNumber = "tves"
    case episodeTitle = "tven"
    case executiveProducer = "©xpd"
    case genre = "©gen"
    case genreID = "geID"
    case initialKey = ".KEY"
    case isrc = "©isr"
    case language = "LANGUAGE"
    case linerNotes = "©lnt"
    case longDescription = "ldes"
    case lyricist = "©aut"
    case lyrics = "©lyr"
    case mediaType = "stik"
    case mood = "MOOD"
    case movementName = "©mvn"
    case movementNumber = "©mvi"
    case movementTotal = "©mvc"
    case narrator = "©nrt"
    case network = "tvnn"
    case onlineExtras = "©url"
    case originalAlbum = "ORIGINAL ALBUM"
    case originalArtist = "©ope"
    case originalFilename = "ORIGINAL FILENAME"
    case originalLyricist = "ORIGINAL LYRICIST"
    case originalYear = "ORIGINAL YEAR"
    case paymentWebpage = "PAYMENT_URL"
    case performer = "©prf"
    case podcast = "pcst"
    case podcastCategory = "catg"
    case podcastDescription = "desc"
    case podcastID = "egid"
    case podcastKeywords = "keyw"
    case podcastUrl = "purl"
    case predefinedGenre = "gnre"
    case phonogramRights = "©phg"
    case producer = "©prd"
    case publisher = "©pub"
    case publisherWebpage = "LABEL_URL"
    case purchaseDate = "purd"
    case radioStation = "RADIO_STATION"
    case radioStationOwner = "STATION_OWNER"
    case radioStationWebpage = "OFFICIAL_RADIO_URL"
    case recordCompany = "©mak"
    case recordingDate = "©day"
    case releaseDate = "rldt"
    case season = "tvsn"
    case series = "tvsh"
    case seriesDescription = "sdes"
    case seriesSort = "sosn"
    case soloist = "©sol"
    case soundEngineer = "©sne"
    case sourceCredit = "©src"
    case subtitle = "©snm"
    case taggingTime = "TAGGINGTIME"
    case thanks = "©thx"
    case title = "©nam"
    case titleSort = "sonm"
    case trackNumber = "trkn"
    case trackSubtitle = "©st3"
    case work = "©wrk"
    case year = "yrrc"

}
