//
//  AtomIdentifier.swift
//  SwiftTaggerMP4
//
//  Created by Nolaine Crusher on 4/21/20.
//  Copyright © 2020 Nolaine Crusher. All rights reserved.
//

import Foundation
import AVFoundation

@available(OSX 10.13, *)
enum Metadata: String, CaseIterable {
    
    case acknowledgment = "©cak"
    case album = "©alb"
    case albumArtist = "aART"
    case albumArtistSort = "soaa"
    case albumSort = "soal"
    case arranger = "©arg"
    case artDirector = "©ard"
    case artist = "©ART"
    case artistSort = "soar"
    case artistWebpage = "©prl"
    case artwork = "covr"
    case audioFileWebpage = "com.apple.iTunes.OFFICIAL_AUDIO_FILE_URL"
    case audioSourceWebpage = "com.apple.iTunes.OFFICIAL_AUDIO_SOURCE_URL"
    case bpm = "tmpo"
    case comment = "©cmt"
    case compilation = "cpil"
    case composer = "©com"
    case composerSort = "soco"
    case conductor = "©con"
    case contentAdvisory = "com.apple.iTunes.iTunEXTC"
    case contentRating = "rtng"
    case copyright = "cprt"
    case copyrightWebpage = "com.apple.iTunes.COPYRIGHT URL"
    case description = "©des"
    case director = "©dir"
    case discNumber = "disk"
    case encodedBy = "©enc"
    case encodingSettings = "com.apple.iTunes.ENCODING"
    case encodingTime = "com.apple.iTunes.ENCODINGTIME"
    case encodingTool = "©too"
    case episodeNumber = "tves"
    case episodeTitle = "tven"
    case executiveProducer = "©xpd"
    case genre = "©gen"
    case predefinedGenre = "genr"
    case genreID = "geID"
    case grouping = "©grp"
    case initialKey = "com.apple.iTunes.KEY"
    case isrc = "©isr"
    case label = "©lab"
    case language = "com.apple.iTunes.LANGUAGE"
    case linerNotes = "©lnt"
    case longDescription = "ldes"
    case lyricist = "©aut"
    case lyrics = "©lyr"
    case mediaType = "stik"
    case mood = "com.apple.iTunes.MOOD"
    case movementName = "©mvn"
    case movementNumber = "©mvi"
    case movementTotal = "©mvc"
    case narrator = "©nrt"
    case network = "tvnn"
    case website = "©url"
    case originalAlbum = "com.apple.iTunes.ORIGINAL ALBUM"
    case originalArtist = "©ope"
    case originalFilename = "com.apple.iTunes.ORIGINAL FILENAME"
    case originalLyricist = "com.apple.iTunes.ORIGINAL LYRICIST"
    case originalYear = "com.apple.iTunes.ORIGINAL YEAR"
    case paymentWebpage = "com.apple.iTunes.PAYMENT_URL"
    case performer = "©prf"
    case podcast = "pcst"
    case podcastCategory = "catg"
    case songDescription = "desc"
    case podcastID = "egid"
    case podcastKeywords = "keyw"
    case podcastUrl = "purl"
    case phonogramRights = "©phg"
    case producer = "©prd"
    case publisher = "©pub"
    case publisherWebpage = "©lal"
    case purchaseDate = "purd"
    case radioStation = "com.apple.iTunes.RADIO_STATION"
    case radioStationOwner = "com.apple.iTunes.STATION_OWNER"
    case radioStationWebpage = "com.apple.iTunes.OFFICIAL_RADIO_URL"
    case recordCompany = "©mak"
    case recordingDate = "©day"
    case releaseDate = "rldt"
    case season = "tvsn"
    case series = "tvsh"
    case seriesDescription = "sdes"
    case seriesSort = "sosn"
    case soloist = "©sol"
    case soundEngineer = "©sne"
    case sourceCredit = "©src"
    case subtitle = "©snm"
    case taggingTime = "com.apple.iTunes.TAGGINGTIME"
    case thanks = "©thx"
    case title = "©nam"
    case titleSort = "sonm"
    case trackNumber = "trkn"
    case trackSubtitle = "©st3"
    case work = "©wrk"
    case writer = "©wrt"
    case year = "yrrc"
    case gaplessPlayback = "pgap"
    case albumID = "akID"
    case appleStoreCountryID = "sfID"
    case conductorID = "cnID"
    case artistID = "atID"
    case playlistID = "plID"
    case composerID = "cmID"
    case seller = "xid "
    case arrangerKeyword = "©ark"
    case composerKeyword = "©cok"
    case copyrightStatement = "©cpy"
    case editDateAndDescription1 = "©ed1"
    case editDateAndDescription2 = "©ed2"
    case editDateAndDescription3 = "©ed3"
    case editDateAndDescription4 = "©ed4"
    case editDateAndDescription5 = "©ed5"
    case editDateAndDescription6 = "©ed6"
    case editDateAndDescription7 = "©ed7"
    case editDateAndDescription8 = "©ed8"
    case editDateAndDescription9 = "©ed9"
    case format = "©fmt"
    case information = "©inf"
    case filmMakerUrl = "©mal"
    case titleKeywords = "©nak"
    case producerKeywords = "©pdk"
    case artistKeywords = "©prk"
    case requirements = "©req"
    case subtitleKeywords = "©snk"
    case songwriterKeywords = "©swk"
    case softwareVersion = "©swr"
    case showWorkAndMovement = "shwm"
    case owner = "ownr"

    var keySpace: AVMetadataKeySpace {
        if self.rawValue.count == 4 {
            return AVMetadataKeySpace(rawValue: "itsk")
        } else {
            return AVMetadataKeySpace(rawValue: "itlk")
        }
    }
}
